### PR TITLE
Some changes & features

### PR DESCRIPTION
**Pull request by umgustavo**
### What i've been added:

- Steam games banners (via Steam CDN)
- Loading games before + spinner animation
- OS username as default username
- Default profile picture
- Check if profile picture is valid, if it's not, reset to default profile picture

PS: I commented the fetch_banner function & IPC for now, bc I don't know and don't have access to lazap API or something

### CODE REVIEW

**Review by Assassin-1234 — COMMENTED** [review]
looks good! can I please have your Discord Tag?

**Comment by umgustavo** [comment]
> looks good! can I please have your Discord Tag?

gustavo#7777

**Review by DashCruft — APPROVED** [review]
Hello this is DashCruft,

First, Thank you so much for this. Your work seems very clean and I fully appreciate your effort! 💜
Second, I've tested this and I'm glad to say this works without any issues and some of the bugs are also solved!

Merging to Nightly now...

**Comment by umgustavo** [comment]
Glad to hear that :)

**Pull request merged**
