### PR TITLE
Auto Game-Detection

### PR DESCRIPTION
**Pull request by LegItMate**
This PR will add functionality for running/managing games through our launcher.

As of right now, the launcher supports:
- Epic Games
- Steam
- Valorant(Riot Games)

Moreover, this PR also focuses on making the GUI better and/or adding functionality for stuff like Recently Played Games, Most Played Games, etc.

Suggestions, additions, and recommendations are accepted! :heart:
The description of this PR will be updated whenever there's anything new or improved.

### CODE REVIEW

**Comment by DashCruft** [comment]
What clients it supports? Like steam, epic games, etc etc

**Comment by LegItMate** [comment]
As of right now, it supports:

- Epic Games
- Steam
- Valorant(Riot Games)

**Comment by DashCruft** [comment]
This is awesome!

and of course, it's windows specific right now correct?

**Comment by DashCruft** [comment]
I will be working on support for Linux

Thank you for your work @LegItMate

**Review by DashCruft — APPROVED** [review]

**Pull request merged**
